# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 2ee2c93
_src_path: https://github.com/vivienm/copier-rust
copyright_holder: Vivien Maisonneuve
copyright_year: 2022
forge: github
github_pages: true
github_repo: rust-tdigest-ch
github_user: vivienm
license: MIT
package_name: tdigest-ch
project_description: A Rust library for estimating quantiles in a stream, using ClickHouse
    t-digest data structure.
project_name: tdigest-ch
project_type: library
rust_toolchain: stable
user_name: Vivien Maisonneuve
