# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 276a4c1
_src_path: gh:vivienm/copier-rust
author_fullname: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_license: MIT
copyright_year: 2022
package_name: tdigest-ch
pages_enabled: true
pages_provider: github.io
pages_url: https://vivienm.github.io/rust-tdigest-ch
project_description: A Rust library for estimating quantiles in a stream, using ClickHouse
    t-digest data structure.
project_name: tdigest-ch
project_type: lib
repository_hosted: true
repository_name: rust-tdigest-ch
repository_namespace: vivienm
repository_provider: github.com
repository_url: https://github.com/vivienm/rust-tdigest-ch
rust_toolchain: nightly
