[advisories]
vulnerability = "deny"
unmaintained = "deny"
unsound = "deny"
yanked = "deny"
notice = "deny"

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
]

[[licenses.exceptions]]
name = "unicode-ident"
allow = ["Unicode-DFS-2016"]
