name: "Continuous integration"

on:
  push:
  pull_request:

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    name: "Check"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "dtolnay/rust-toolchain@nightly"
    - run: "cargo check --all-features"

  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "dtolnay/rust-toolchain@nightly"
    - run: "cargo test --all-features"

  fmt:
    name: "Fmt"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "dtolnay/rust-toolchain@nightly"
      with:
        components: "rustfmt"
    - run: "cargo fmt --all -- --check"

  clippy:
    name: "Clippy"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "dtolnay/rust-toolchain@nightly"
      with:
        components: "clippy"
    - run: "cargo clippy -- -D warnings"

  doc:
    name: "Doc"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "dtolnay/rust-toolchain@nightly"
    - run: "cargo rustdoc --all-features -- -D warnings"
    - if: "github.ref == format('refs/heads/{0}', github.event.repository.default_branch)"
      uses: "actions/upload-pages-artifact@v1"
      with:
        path: "./target/doc"

  typos:
    name: "Typos"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: crate-ci/typos@master

  deny:
    name: "Deny"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "EmbarkStudios/cargo-deny-action@v1"

  pages:
    if: "github.ref == format('refs/heads/{0}', github.event.repository.default_branch)"
    needs: "doc"
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-latest"
    steps:
    - id: "deployment"
      uses: "actions/deploy-pages@v1"
